version: '3.2'

services:
  frontend:
    build: frontend
    volumes:
      - ./frontend:/src/frontend
      - /src/frontend/node_modules
  api-tests:
    build: api-tests
    volumes:
      - ./api-tests:/src/api-tests
      - /src/api-tests/node_modules
