version: '3.2'

services:
  backend:
    build: backend
    volumes:
      - ./backend:/src/backend
      - ./frontend/dist:/src/frontend/dist
      - /src/backend/node_modules
    ports:
      - 8080:8080 # main port
  frontend:
    build: frontend
    image: poc-vue-authenticate/frontend
    volumes:
      - ./frontend:/src/frontend
      - /src/frontend/node_modules
    ports:
     - 35729:35729 # livereload
  api-tests:
    build: api-tests
    volumes:
      - ./api-tests:/src/api-tests
      - /src/api-tests/node_modules
